add idempotency docs
novuhq/docs pull request #202
Opened 2023-10-11 01:27 UTC by mahendraHegde

for https://github.com/novuhq/novu/issues/4469

2023-10-11 09:02 UTC, unicodeveloper approved these changes

2023-10-26 15:45 UTC, rifont commented
@mahendraHegde Deliveroo have adopted the same Idempotency approach, albeit with slightly different naming. You may like to use them as a reference:
https://api-docs.deliveroo.com/docs/signature-idempotent-requests

2023-10-28 01:19 UTC, mahendraHegde commented
@unicodeveloper  docs re readt to be reviewed
@rifont  i added the docs at path `additional-resources/idempotency` as it seems the std used in docs, so we might need to change `Link` response header in the api as well

2023-10-30 09:44 UTC, rifont requested changes

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +2. If the request parameters do not match the initial request, the API returns an `Unprocessable Entity` error.
We are only checking on the request body currently.

```suggestion
2. If the request body does not match the initial request, the API returns a `422 Unprocessable Entity` error.
```

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +1. If the `<key>` exceeds 255 characters, the API will respond with a `Bad Request` error.
Including the status code for quicker reference.

```suggestion
1. If the `<key>` exceeds 255 characters, the API will respond with a `400 Bad Request` error.
```

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +When a response is replayed, an `Idempotent-Replay: true` header is included in the response.
This is one of the implementation details we have different to Deliveroo.

```suggestion
When a response is replayed, an `Idempotency-Replay: true` header is included in the response.
```

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +When you make idempotent requests, the API stores the status code and response body from the initial request. If the same idempotency key is used in another request, the API replays the saved respons
Small change for readability and formality.

```suggestion
When you make idempotent requests, the API stores the status code and response body from the initial request. If the same idempotency key is used in another request, the API replays the saved response, including for client and server error responses like 400 and 500 errors.
```

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +
```suggestion
---
title: 'Idempotent Requests'
description: 'Learn how to retry API requests without performing the same operation twice'
---

```

2023-10-30 09:44 UTC, rifont commented on additional-resources/idempotency.mdx
> +3. If the initial request is still being processed concurrently and hasn't yet responded, the API returns a `Conflict` error along with a `Retry-After` header.
```suggestion
3. If the initial request is still being processed concurrently and hasn't yet responded, the API returns a `409 Conflict` error along with a `Retry-After` header.
```

2023-10-30 09:44 UTC, rifont commented on mint.json
> +        "additional-resources/idempotency"
Closer grouping of Rate Limits and Idempotency as they are related with retry behaviour.

```suggestion
        "additional-resources/idempotency",
        "additional-resources/glossary"
```

2023-10-30 09:47 UTC, rifont requested changes

2023-10-30 09:47 UTC, rifont commented on additional-resources/idempotency.mdx
> +Novu supports retrying and concurrent requests for `POST` and `PATCH` APIs, ensuring the safety and reliability of your requests, particularly in scenarios where network issues or communication probl
```suggestion
Novu supports retrying and concurrent requests for `POST` and `PATCH` operations, ensuring the safety and reliability of your requests, particularly in scenarios where network issues or communication problems can introduce uncertainty into request outcomes.
```

2023-10-30 09:50 UTC, rifont requested changes

2023-10-30 09:50 UTC, rifont commented on additional-resources/idempotency.mdx
> +Novu supports retrying and concurrent requests for `POST` and `PATCH` operations, ensuring the safety and reliability of your requests, particularly in scenarios where network issues or communication
Adding context relevant to Novu.

```suggestion
Novu supports retrying and concurrent requests for `POST` and `PATCH` operations, ensuring the safety and reliability of your requests, particularly in scenarios where network issues or communication problems can introduce uncertainty into request outcomes. Idempotent requests are essential for business-critical applications, such as for ensuring only once delivery of your notifications.
```

2023-10-30 09:50 UTC, rifont approved these changes

2023-10-30 09:51 UTC, rifont commented
Great work @mahendraHegde ! Thanks for your contribution 🎉

2023-10-30 09:51 UTC, merged