Added info about the `equals` helper [Ticket DVRL-89]
novuhq/docs pull request #391
Opened 2023-11-26 23:33 UTC by iampearceman

![Screenshot 2023-11-27 at 1 33 05](https://github.com/novuhq/docs/assets/63902456/39fcb586-66e8-42b5-9719-fc72a1c39202)

2023-11-27 07:31 UTC, jainpawan21 requested changes

2023-11-27 07:31 UTC, jainpawan21 commented on content-creation-design/handlebars-helpers.mdx
> +}
remove values array because it is not used in template example
```suggestion
{
  "value1" : 10,
  "values2" : 1
}
```

2023-11-27 08:05 UTC, jainpawan21 commented
Look into merge conflict as well

2023-12-05 06:55 UTC, unicodeveloper approved these changes

2023-12-05 06:56 UTC, merged