FCM Push provider guide with iOS app [Ticket DVRL-115]
novuhq/docs pull request #466
Opened 2024-01-15 04:57 UTC by iampearceman

https://github.com/novuhq/docs/assets/63902456/84b2efd1-cfb1-49bc-aa96-7fdbdd572038

2024-01-15 05:10 UTC, sumitsaurabh927 requested changes
There are a lot of grammatical errors. Please run it through grammarly once @iampearceman 

I'll re-review it afterwards

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +description: 'Leverage the digest functionality to send email notifications'
Digest?

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +description: 'Leverage the digest functionality to send email notifications'
This needs to change @iampearceman

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +- Laptop running macOS to develop an iOS project
A machine running MacOS to work on an iOS project

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +- [Xcode](https://developer.apple.com/xcode/) installed on your Mac
installed on your machine

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +Go to the firebase documentation website go to docs right here and select cloud messaging we're going to be following this guide to set up
select 'Cloud Messaging'

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +Go to the firebase documentation website go to docs right here and select cloud messaging we're going to be following this guide to set up
Go to the Firebase docs, and select 'Cloud Messaging'. We're going to follow this guide to add cloud messaging to our app.

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +you can read more about how firebase
You can read more about how Firebase Cloud Messaging works in their [official docs](link)

2024-01-15 05:10 UTC, sumitsaurabh927 commented on guides/FCM-iOS-Novu/how-to-send-PUSH-notifications-to-iOS-devices-with-FCM-using-Novu.mdx
> +Go over here to ios and click on set up
ios -> iOS

2024-01-16 06:11 UTC, unicodeveloper approved these changes

2024-01-16 06:11 UTC, unicodeveloper commented
Hey @iampearceman What about the link to the accompanying repo/code for this guide?

2024-01-16 06:48 UTC, jainpawan21 commented
Amazing work emil 🚀

2024-01-16 06:48 UTC, jainpawan21 approved these changes

2024-01-16 11:10 UTC, sumitsaurabh927 approved these changes

2024-01-16 11:12 UTC, merged