Update Idempotency Documentation
novuhq/docs pull request #583
Opened 2024-04-26 16:12 UTC by Cliftonz

2024-04-27 11:46 UTC, BiswaViraj requested changes

2024-04-27 11:46 UTC, BiswaViraj commented on additional-resources/idempotency.mdx
> +description: 'Retry API requests fearlessly, ensuring operation performance just once!'
```suggestion
description: 'Retry API requests fearlessly, ensuring the operation performs just once!'
```
;)

2024-05-02 04:21 UTC, jainpawan21 reviewed
JS code formatting issue

2024-05-02 04:21 UTC, jainpawan21 commented on additional-resources/idempotency.mdx
> +            );
```suggestion
        await novu.trigger("<WORKFLOW_TRIGGER_IDENTIFIER>", {
          to: {
            subscriberId: "<UNIQUE_SUBSCRIBER_IDENTIFIER>",
          },
          payload: {
            name: "Hello World",
          },
          actor: "actorId",
          tenant: "tenantIdentifier",
        });
```

2024-05-02 04:21 UTC, jainpawan21 commented on additional-resources/idempotency.mdx
> +            );
```suggestion
        await novu.trigger("<WORKFLOW_TRIGGER_IDENTIFIER>", {
          to: {
            subscriberId: "<UNIQUE_SUBSCRIBER_IDENTIFIER>",
          },
          payload: {
            name: "Hello World",
          },
          actor: "actorId",
          tenant: "tenantIdentifier",
        });
```

2024-05-09 11:25 UTC, jainpawan21 approved these changes

2024-05-09 11:26 UTC, merged